---
- hosts: 54.211.133.110
  become: true
  tasks:
    - name: Install Apache Server
      yum:
        name: httpd
        state: present
    - name:
      service:
        name: httpd
        enabled: true
    - name: Install git
      yum:
        name: git
        state: present
---                